name: Streamlit app CI 

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Check out code
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PAT }} # `PAT` is a secret that contains your Personal Access Token with `write:packages` scope     

      - name: Build and push streamlit-app image
        id: build-and-push
        uses: docker/build-push-action@v4.2.1
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/youcefguichi/streamlit-app:${{github.sha}}     
  # shipping-artifact:
  #   runs-on: ubuntu-latest
  #   name: "Shipping artifact"

  #   needs: build-push
  #   if: github.ref_name == 'main'

  #   steps:
  #     - name: Check out
  #       uses: actions/checkout@v3.0.1
  #       with:
  #         fetch-depth: 1

  #     - name: Shipping release artifact to Gimlet
  #       id: shipping
  #       uses: gimlet-io/gimlet-artifact-shipper-action@v0.5.3
  #       env:
  #         GIMLET_SERVER: ${{ secrets.GIMLET_SERVER }}
  #         GIMLET_TOKEN: ${{ secrets.GIMLET_TOKEN }}

  #     - name: Artifact ID
  #       run: echo "Artifact ID is ${{ steps.shipping.outputs.artifact-id }}"
